name: "Validate Substances Data JSON"

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate JSON
        id: validate
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq -r . ./data/final_updated_drugs.json
          multiline: true

      - name: Print formatted JSON data
        run: |
          printf '%s' "${{ steps.validate.outputs.value }}"
