name: "Validate Substances Data JSON"

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
    
permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate JSON
        run: cat ./data/final_updated_drugs.json | json_pp

