name: "Validate Substances Data JSON"

on:
  push:
    branches:
      - '**'
    paths:
      - '**.json'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - '**'
    paths:
      - '**.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache JSON validation
        id: cache-json
        uses: actions/cache@v3
        with:
          path: ./data/final_validated_drugs.json
          key: json-validation-${{ hashFiles('./data/final_updated_drugs.json') }}
          restore-keys: |
            json-validation-${{ hashFiles('./data/final_updated_drugs.json') }}

      - name: Validate JSON
        id: validate
        if: steps.cache-json.outputs.cache-hit != 'true'
        uses: sergeysova/jq-action@v2
        with:
          cmd: |
            jq -r . ./data/final_updated_drugs.json > ./data/final_validated_drugs.json
          multiline: true

      - name: Print formatted JSON data
        run: cat ./data/final_validated_drugs.json
